# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='default', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
