# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20171109_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pin',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
