# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
