# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20171124_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
