# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_post_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(1, 'Forum Post'), (1, 'Comment'), (3, 'Assignment'), (4, 'Assignment Submission')], default=1),
        ),
    ]
