# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
