# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20171213_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
