# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20171109_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accept_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grades_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
