# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20171109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='publish_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
