# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20171109_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
