# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20171109_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
